# ============================== Filebeat Configuration ==============================

# Configure the Filebeat inputs
filebeat.inputs:
  - type: filestream
    id: my-filestream-id
    paths:
      - /var/log/*.log


output.logstash:
  hosts: ["logstash:5044"]

processors:
  - add_docker_metadata:
      host: "unix:///host_docker/docker.sock"



