receivers:
  otlp:
    protocols:
      grpc:
      http:
processors:
  batch:
exporters:
  otlp:
    endpoint: "otel-collector:4317"  # Ensure this endpoint matches your OTLP receiver configuration
  prometheus:
    endpoint: "0.0.0.0:55681"

extensions:
  zpages:
    endpoint: 0.0.0.0:13133

service:
  extensions: [zpages]
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]
